import subprocess
import json
import os
import requests
from flask import Flask, jsonify
from dotenv import load_dotenv
from collections import defaultdict

load_dotenv()

app = Flask(__name__, static_folder='.')

GITHUB_USER   = os.getenv('GITHUB_USERNAME', 'mauryasagar')
GITHUB_REPO   = os.getenv('GITHUB_REPO', 'devs_first_mate')
GITHUB_TOKEN  = os.getenv('GITHUB_TOKEN', '')
SLACK_CHANNEL = os.getenv('SLACK_CHANNEL_ID', '')


def get_github_issues():
    headers = {'Authorization': f'token {GITHUB_TOKEN}'} if GITHUB_TOKEN else {}
    url = f'https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/issues?state=open&per_page=10'
    try:
        r = requests.get(url, headers=headers)
        data = r.json()
        return [{'number': i['number'], 'title': i['title'], 'state': 'open', 'created_at': i['created_at'], 'user_login': i['user']['login']} for i in data if 'pull_request' not in i], None
    except Exception as e:
        return [], str(e)


def get_github_prs():
    headers = {'Authorization': f'token {GITHUB_TOKEN}'} if GITHUB_TOKEN else {}
    url = f'https://api.github.com/repos/{GITHUB_USER}/{GITHUB_REPO}/pulls?state=closed&per_page=5'
    try:
        r = requests.get(url, headers=headers)
        data = r.json()
        return [{'number': p['number'], 'title': p['title'], 'merged_at': p.get('merged_at'), 'user_login': p['user']['login']} for p in data if p.get('merged_at')], None
    except Exception as e:
        return [], str(e)


def find_duplicates(issues):
    stop_words = {'the','and','for','are','but','not','you','all','can','had','was','one','our','out','get','has','how','its','may','new','now','old','see','who','did','let','put','say','too','use','add','bug','fix','page','issue','error'}
    keyword_map = defaultdict(list)
    for issue in issues:
        title = issue.get('title', '').lower()
        words = set(w for w in title.split() if len(w) > 3 and w not in stop_words)
        for word in words:
            keyword_map[word].append(issue)
    duplicates = []
    seen_pairs = set()
    for word, group in keyword_map.items():
        if len(group) > 1:
            for i in range(len(group)):
                for j in range(i + 1, len(group)):
                    a = group[i].get('number')
                    b = group[j].get('number')
                    pair = tuple(sorted([a, b]))
                    if pair not in seen_pairs:
                        seen_pairs.add(pair)
                        duplicates.append({
                            'issue_a': group[i],
                            'issue_b': group[j],
                            'matched_keyword': word
                        })
    return duplicates


def draft_release_notes(prs):
    if not prs:
        return None
    lines = ["## Release Notes\n", "### What's Changed\n"]
    for pr in prs:
        title = pr.get('title', 'Untitled')
        number = pr.get('number', '?')
        user = pr.get('user_login', 'unknown')
        lines.append(f"- {title} (#{number}) — @{user}")
    lines.append(f"\n**Full Changelog**: https://github.com/{GITHUB_USER}/{GITHUB_REPO}/commits/main")
    lines.append("\n_Auto-generated by Dev's First Mate · Powered by Coral_")
    return '\n'.join(lines)


@app.route('/')
def home():
    return app.send_static_file('index.html')


@app.route('/api/attention')
def get_attention():
    issues, _ = get_github_issues()
    prs, _ = get_github_prs()
    duplicates = find_duplicates(issues or [])
    release_notes = draft_release_notes(prs)

    return jsonify({
        'issues': issues or [],
        'prs': prs or [],
        'cross_join': [],
        'slack': [],
        'duplicates': duplicates,
        'release_notes': release_notes,
        'status': 'ok'
    })


@app.route('/api/health')
def health():
    return jsonify({'status': 'ok', 'github_user': GITHUB_USER, 'repo': GITHUB_REPO})


if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    app.run(debug=False, host='0.0.0.0', port=port)
